{% set name = "progressbar2" %}
{% set version = "4.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: fe48c8955a84428af77bff2642ba47041e1b8f7c867a5b7cc94f8bc255a8f0cf
  - url: https://github.com/wolph/python-progressbar/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 117cd33f2a965b59546828e082457a5c7e23416100fc96412875efdd322724ee
    folder: gh

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools-scm
  run:
    - python
    - python-utils >=3.8.1

test:
  source_files:
    - gh/tests
    - gh/examples.py
    - gh/pytest.ini
    - gh/docs
  imports:
    - progressbar
    - progressbar.__main__
    - progressbar.env
    - progressbar.terminal
    - progressbar.terminal.base
    - progressbar.terminal.stream
  requires:
    - pip
    - pytest >=4.6.9
    - freezegun >=0.3.11
    - dill >=0.3.6
    - pywin32  # [win]
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - cd gh && python -m pytest tests --ignore=tests/console --ignore=tests/test_readme_demos.py --ignore=tests/test_docs_examples.py

about:
  home: https://github.com/WoLpH/python-progressbar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python Progressbar library to provide visual (yet text based) progress to long running operations.
  description: |
    A text progress bar is typically used to display the progress of a long running operation, providing a visual cue that processing is underway.
    The progressbar is based on the old Python progressbar package that was published on the now defunct Google Code. Since that project was completely abandoned by its developer and the developer did not respond to email, I decided to fork the package. This package is still backwards compatible with the original progressbar package so you can safely use it as a drop-in replacement for existing project.
    The ProgressBar class manages the current progress, and the format of the line is given by a number of widgets. A widget is an object that may display differently depending on the state of the progress bar. There are many types of widgets:

    - AbsoluteETA
    - AdaptiveETA
    - AdaptiveTransferSpeed
    - AnimatedMarker
    - Bar
    - BouncingBar
    - Counter
    - CurrentTime
    - DataSize
    - DynamicMessage
    - ETA
    - FileTransferSpeed
    - FormatCustomText
    - FormatLabel
    - FormatLabelBar
    - GranularBar
    - Percentage
    - PercentageLabelBar
    - ReverseBar
    - RotatingMarker
    - SimpleProgress
    - Timer

    The progressbar module is very easy to use, yet very powerful. It will also automatically enable features like auto-resizing when the system supports it.
  doc_url: https://progressbar-2.readthedocs.org
  dev_url: https://github.com/WoLpH/python-progressbar

extra:
  recipe-maintainers:
    - maartenbreddels
    - WoLpH
