travis:
  secure:
    BINSTAR_TOKEN: QIOgHgXtiIhfhbajeCPWR/85ZOBzCbJhC2Z/xF0GerbPAwzT+2fjq+qKhZOpGw4y89WnV+Y4e9ppC31+PP0sb4TcYkzglyZK2lJsa/UTSvaBHkYuQIN2vvaFp9p1OirKuhFVc7WU9buSU6fhSQZUU28ZF7HkfaNONXkXCNKBlvzk4t5R9X0VxiO8cxhVOs1lFudGIgtAhENwMkQyL+VoFVZ0u5oo0SCAleT2VTG0ehvwHBVUEzaM5r+tvoc6W2bSYhHZwf1LMTf/wX3ecOuYLcYwDoLvq6u++0I/zs3vrxdW75yaKDI8s1vQKhCbmM8YpfKn/eVQ+WMOfRnubu3ZpIDSO93imYlTl2XFE5YTszq7RuOY2/7KdQ0MoMxVf3nDJMWsHFjCih1iJyfijsQnDyibhcEh108apW9dW7mT8EDN0P4KZwbfB4OtSpDJUMRWy2lQQmiAUXnXoLFRoYSQ5tBHGYk0AqNVI1JMTasZbyeIDxIYNxhHpkryMWmtnuPjoMRQreQh1W0TwXy6TqsNN4klyrzPIsUDATUveSnWzY7fzaeYpyX+O6bMIxSo0ltRz80LwqDgpPR3aOy33NvL/Mel/AR8B3+ENz/7TXrTpH9spTg/rKGYZU7LjyDArwy3RPLziOQqdwLI5tzyjPSh0P1vdAXn4rTsjPVbQVsE88s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
